spring.application.name=ai-investigation-service

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5433/aegisops
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true